#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : reportlab
Version  : 3.5.9
Release  : 15
URL      : https://files.pythonhosted.org/packages/6d/40/e0230c95234a16accad10bb50228b3b274c92797c92bcc423db70e0396c0/reportlab-3.5.9.tar.gz
Source0  : https://files.pythonhosted.org/packages/6d/40/e0230c95234a16accad10bb50228b3b274c92797c92bcc423db70e0396c0/reportlab-3.5.9.tar.gz
Summary  : The Reportlab Toolkit
Group    : Development/Tools
License  : BSD-3-Clause LGPL-2.0
Requires: reportlab-python3
Requires: reportlab-license
Requires: reportlab-python
BuildRequires : Pillow
BuildRequires : buildreq-distutils3
BuildRequires : python3-dev

%description
This directory is the home of various ReportLab tools.
They are packaged such that they can be used more easily.

%package license
Summary: license components for the reportlab package.
Group: Default

%description license
license components for the reportlab package.


%package python
Summary: python components for the reportlab package.
Group: Default
Requires: reportlab-python3 = %{version}-%{release}

%description python
python components for the reportlab package.


%package python3
Summary: python3 components for the reportlab package.
Group: Default
Requires: python3-core

%description python3
python3 components for the reportlab package.


%prep
%setup -q -n reportlab-3.5.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1538496443
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/reportlab
cp LICENSE.txt %{buildroot}/usr/share/doc/reportlab/LICENSE.txt
cp src/reportlab/license.txt %{buildroot}/usr/share/doc/reportlab/src_reportlab_license.txt
cp src/rl_addons/renderPM/libart_lgpl/COPYING %{buildroot}/usr/share/doc/reportlab/src_rl_addons_renderPM_libart_lgpl_COPYING
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/doc/reportlab/LICENSE.txt
/usr/share/doc/reportlab/src_reportlab_license.txt
/usr/share/doc/reportlab/src_rl_addons_renderPM_libart_lgpl_COPYING

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
