#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : reportlab
Version  : 3.5.28
Release  : 31
URL      : https://files.pythonhosted.org/packages/af/62/72ad234b39a9d9108a5f70f04f5b8d6798831a3b8180fad72c4c3ce52dec/reportlab-3.5.28.tar.gz
Source0  : https://files.pythonhosted.org/packages/af/62/72ad234b39a9d9108a5f70f04f5b8d6798831a3b8180fad72c4c3ce52dec/reportlab-3.5.28.tar.gz
Summary  : The Reportlab Toolkit
Group    : Development/Tools
License  : BSD-3-Clause LGPL-2.0 OFL-1.0
Requires: reportlab-license = %{version}-%{release}
Requires: reportlab-python = %{version}-%{release}
Requires: reportlab-python3 = %{version}-%{release}
Requires: Pillow
BuildRequires : Pillow
BuildRequires : buildreq-distutils3
BuildRequires : python3-dev

%description
This directory is the home of various ReportLab tools.
They are packaged such that they can be used more easily.

%package license
Summary: license components for the reportlab package.
Group: Default

%description license
license components for the reportlab package.


%package python
Summary: python components for the reportlab package.
Group: Default
Requires: reportlab-python3 = %{version}-%{release}

%description python
python components for the reportlab package.


%package python3
Summary: python3 components for the reportlab package.
Group: Default
Requires: python3-core

%description python3
python3 components for the reportlab package.


%prep
%setup -q -n reportlab-3.5.28

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1570061702
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/reportlab
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/reportlab/LICENSE.txt
cp src/reportlab/fonts/bitstream-vera-license.txt %{buildroot}/usr/share/package-licenses/reportlab/src_reportlab_fonts_bitstream-vera-license.txt
cp src/reportlab/license.txt %{buildroot}/usr/share/package-licenses/reportlab/src_reportlab_license.txt
cp src/rl_addons/renderPM/libart_lgpl/COPYING %{buildroot}/usr/share/package-licenses/reportlab/src_rl_addons_renderPM_libart_lgpl_COPYING
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/reportlab/LICENSE.txt
/usr/share/package-licenses/reportlab/src_reportlab_fonts_bitstream-vera-license.txt
/usr/share/package-licenses/reportlab/src_reportlab_license.txt
/usr/share/package-licenses/reportlab/src_rl_addons_renderPM_libart_lgpl_COPYING

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
